bootstrap_common: &bootstrap_common
  pull: true
  commands:
    - mkdir -p /opt/metwork-mfserv-${DRONE_BRANCH}
    - ./bootstrap.sh /opt/metwork-mfserv-${DRONE_BRANCH} /opt/metwork-mfcom-$${MFEXT_BRANCH}
    - cat adm/root.mk

build_common: &build_common
  commands:
    - mkdir -p /opt/metwork-mfserv-${DRONE_BRANCH}
    - make
    - make doc
    - rm -Rf html_doc
    - cp -Rf /opt/metwork-mfserv-${DRONE_BRANCH}/html_doc .
    - make test
    - make RELEASE_BUILD=${DRONE_BUILD_NUMBER} rpm
    - mv /opt/metwork-mfserv-${DRONE_BRANCH}/*.rpm .  
    
publish_ci_common: &publish_ci_common
  commands:
    - mkdir -p /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
    - cp *.rpm /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
    - yum -y install createrepo
    - createrepo --update /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}
    - if test "${OS_VERSION}" = "centos6"; then rm -Rf /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfserv; mkdir -p /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfserv ; cp -Rf html_doc/* /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfserv/ ; fi
  volumes:
    - /pub:/pub
  
pipeline:
  bootstrap_integration:
    image: metwork/mfxxx-${OS_VERSION}-buildimage:integration
    environment:
      - MFEXT_BRANCH=integration
    <<: *bootstrap_common
    when:
      event: [push, pull_request]
      branch: integration
  bootstrap:
    image: metwork/mfxxx-${OS_VERSION}-buildimage:master
    environment:
      - MFEXT_BRANCH=master
    <<: *bootstrap_common
    when:
      event: [push, pull_request]
      branch:
        exclude: [ integration ]  
  build_integration:
    <<: *build_common
    image: metwork/mfxxx-${OS_VERSION}-buildimage:integration
    when:
      event: [push, pull_request]
      branch: integration
  build:
    <<: *build_common
    image: metwork/mfxxx-${OS_VERSION}-buildimage:master
    when:
      event: [push, pull_request]
      branch:
        exclude: [ integration ]  
  publish_ci_integration:
    <<: *publish_ci_common
    image: metwork/mfxxx-${OS_VERSION}-buildimage:integration
    when:
      event: [push]
      branch: integration
  publish_ci:
    <<: *publish_ci_common
    image: metwork/mfxxx-${OS_VERSION}-buildimage:master
    when:
      event: [push]
      branch:
        exclude: [ integration ]

matrix:
  OS_VERSION:
    - centos6
    - centos7
